ALTER TABLE `Incident`
  ADD COLUMN `occurrenceCount` INT NOT NULL DEFAULT 1,
  ADD COLUMN `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `needsHumanReview` BOOLEAN NOT NULL DEFAULT FALSE;
