import { Container, Card, Input, Button, Textarea, Badge, PageHeader, Pill } from "@/components/ui";
import Link from "next/link";
import { requireSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

function MiniStep({ n, title, text }: { n: string; title: string; text: string }) {
  return (
    <div className="rounded-[1.4rem] border border-slate-200/80 bg-white/85 p-4 shadow-sm">
      <div className="flex items-start gap-3">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-2xl bg-slate-950 text-sm font-semibold text-white">{n}</div>
        <div>
          <div className="font-semibold text-slate-950">{title}</div>
          <p className="mt-1 text-sm leading-6 text-slate-600">{text}</p>
        </div>
      </div>
    </div>
  );
}

export default async function NewTenant() {
  const s = await requireSession();
  const ws = await prisma.workspace.findUnique({ where: { id: s.wid }, select: { name: true } });
  const cfg = await prisma.mailstackConfig.findUnique({ where: { workspaceId: s.wid } });

  return (
    <Container wide>
      <div className="space-y-8">
        <PageHeader
          title="Create MailStack Tenant"
          subtitle="Launch a full tenant with domains, outbound IPs, mailbox users, DKIM/SPF/DMARC defaults, and Cloudflare provisioning in one guided flow."
          right={
            <>
              <Badge>{ws?.name || "Workspace"}</Badge>
              {cfg?.cloudflareTokenEnc ? <Pill tone="success">Cloudflare token set</Pill> : <Pill tone="warning">Cloudflare token missing</Pill>}
              <Link href="/app/mailstack"><Button variant="ghost">Back to Mailstack</Button></Link>
            </>
          }
        />

        <div className="grid gap-4 lg:grid-cols-3">
          <MiniStep n="1" title="Name the tenant" text="Use a simple identifier like sial, client1, or brand-us. It becomes the server-side tenant workspace." />
          <MiniStep n="2" title="Add domains + IPs" text="Paste domains and outbound IPs line-by-line. MailStack will prepare DNS defaults and rotation settings." />
          <MiniStep n="3" title="Create mailboxes" text="Define mailbox users. Passwords are generated by the script and imported encrypted into ColdMailPro." />
        </div>

        <form className="grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(360px,0.75fr)]" action="/api/mailstack/tenant/create" method="post">
          <Card title="Tenant blueprint" subtitle="Core identity, DNS defaults, outbound IP pool, and mailbox users.">
            <div className="grid gap-5">
              <div className="grid gap-4 md:grid-cols-2">
                <label className="grid gap-2 text-sm font-medium text-slate-700">
                  Tenant name
                  <Input name="name" placeholder="tenant1" required />
                  <span className="text-xs font-normal text-slate-500">Lowercase identifiers are easiest to manage on the server.</span>
                </label>
                <label className="grid gap-2 text-sm font-medium text-slate-700">
                  Server IP
                  <Input name="serverIp" defaultValue={cfg?.serverIp || ""} placeholder="51.38.38.222" required />
                  <span className="text-xs font-normal text-slate-500">Used for HELO/MX guidance and provisioning scripts.</span>
                </label>
              </div>

              <div className="grid gap-4 md:grid-cols-2">
                <label className="grid gap-2 text-sm font-medium text-slate-700">
                  Domains
                  <Textarea name="domains" rows={9} placeholder={"example.com\nexample.net"} required className="font-mono text-sm" />
                  <span className="text-xs font-normal text-slate-500">One domain per line. Duplicates are ignored by the server job.</span>
                </label>
                <label className="grid gap-2 text-sm font-medium text-slate-700">
                  Outbound IPs
                  <Textarea name="ips" rows={9} placeholder={"15.204.159.169\n15.204.159.170"} required className="font-mono text-sm" />
                  <span className="text-xs font-normal text-slate-500">One IP per line. These become SPF suggestions and rotation candidates.</span>
                </label>
              </div>

              <label className="grid gap-2 text-sm font-medium text-slate-700">
                Mailbox users to create
                <Textarea name="users" rows={7} placeholder={"info@example.com\nsales@example.com\nsupport@example.com"} required className="font-mono text-sm" />
                <span className="text-xs font-normal text-slate-500">Passwords are auto-generated by the script and imported into the app encrypted.</span>
              </label>
            </div>
          </Card>

          <div className="grid gap-6 content-start">
            <Card title="DNS defaults" subtitle="Templates applied during provisioning.">
              <div className="grid gap-4">
                <label className="grid gap-2 text-sm font-medium text-slate-700">
                  HELO template
                  <Input name="heloTemplate" defaultValue={cfg?.heloTemplate || "mail.%d"} />
                  <span className="text-xs font-normal text-slate-500">%d = domain</span>
                </label>
                <label className="grid gap-2 text-sm font-medium text-slate-700">
                  DMARC policy
                  <Input name="dmarcPolicy" defaultValue={cfg?.dmarcPolicy || "none"} />
                </label>
                <label className="grid gap-2 text-sm font-medium text-slate-700">
                  DMARC RUA template
                  <Input name="dmarcRuaTemplate" defaultValue={cfg?.dmarcRuaTemplate || "dmarc@%d"} />
                  <span className="text-xs font-normal text-slate-500">%d = domain</span>
                </label>
                <label className="flex items-center gap-3 rounded-2xl border border-slate-200/80 bg-white/80 p-3 text-sm text-slate-700">
                  <Input type="checkbox" name="createZones" defaultChecked />
                  Create Cloudflare zones when missing
                </label>
              </div>
            </Card>

            <Card title="Launch provisioning" subtitle="Queues the worker job and starts tenant setup on the server.">
              <div className="space-y-3 text-sm leading-6 text-slate-600">
                <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-800">Provisioning will run DNS preparation, mailbox creation, and app import once the worker picks up the job.</div>
                {!cfg?.cloudflareTokenEnc ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-amber-800">Cloudflare token is not set. You can still create the tenant, but DNS sync may require token setup first.</div> : null}
              </div>
              <div className="mt-5 grid gap-2">
                <Button type="submit" className="w-full">Create tenant & queue provisioning</Button>
                <Link href="/app/mailstack" className="w-full"><Button variant="ghost" type="button" className="w-full">Cancel</Button></Link>
              </div>
            </Card>
          </div>
        </form>
      </div>
    </Container>
  );
}
