import { Container, Card, Input, Button, Textarea, Badge } from "@/components/ui";
import Link from "next/link";
import { requireSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function NewTenant() {
  const s = await requireSession();
  const cfg = await prisma.mailstackConfig.findUnique({ where: { workspaceId: s.wid } });

  return (
    <Container>
      <div className="grid gap-6">
        <Card title="Create mail tenant">
          <p className="opacity-80 text-sm">
            A <b>tenant</b> groups domains + outbound IPs + mailboxes. After creation, the worker will run <code>mailstack-addon.sh tenant-setup</code>.
          </p>

          <form className="mt-4 grid gap-4" action="/api/mailstack/tenant/create" method="post">
            <div className="grid md:grid-cols-2 gap-3">
              <div>
                <div className="text-xs opacity-70 mb-1">Tenant name (identifier)</div>
                <Input name="name" placeholder="tenant1" required />
              </div>
              <div>
                <div className="text-xs opacity-70 mb-1">Server IP</div>
                <Input name="serverIp" defaultValue={cfg?.serverIp || ""} placeholder="51.38.38.222" required />
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-3">
              <div>
                <div className="text-xs opacity-70 mb-1">Domains (one per line)</div>
                <Textarea name="domains" rows={8} placeholder={"example.com\nexample.net"} required />
              </div>
              <div>
                <div className="text-xs opacity-70 mb-1">Outbound IPs (one per line)</div>
                <Textarea name="ips" rows={8} placeholder={"15.204.159.169\n15.204.159.170"} required />
              </div>
            </div>

            <div>
              <div className="text-xs opacity-70 mb-1">Mailbox users to create (one email per line)</div>
              <Textarea name="users" rows={6} placeholder={"info@example.com\nsales@example.com"} required />
              <div className="text-xs opacity-60 mt-1">Passwords are auto-generated by the script and imported into the app (encrypted).</div>
            </div>

            <div className="grid md:grid-cols-3 gap-3">
              <div>
                <div className="text-xs opacity-70 mb-1">HELO template</div>
                <Input name="heloTemplate" defaultValue={cfg?.heloTemplate || "mail.%d"} />
                <div className="text-xs opacity-60 mt-1">%d = domain</div>
              </div>
              <div>
                <div className="text-xs opacity-70 mb-1">DMARC policy</div>
                <Input name="dmarcPolicy" defaultValue={cfg?.dmarcPolicy || "none"} />
              </div>
              <div>
                <div className="text-xs opacity-70 mb-1">DMARC RUA template</div>
                <Input name="dmarcRuaTemplate" defaultValue={cfg?.dmarcRuaTemplate || "dmarc@%d"} />
                <div className="text-xs opacity-60 mt-1">%d = domain</div>
              </div>
            </div>

            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" name="createZones" defaultChecked />
              Create Cloudflare zones (if missing)
            </label>

            <div className="flex gap-3">
              <Button type="submit">Create tenant & queue provisioning</Button>
              <Link href="/app/mailstack"><Button variant="ghost">Back</Button></Link>
            </div>

            {!cfg?.cloudflareTokenEnc ? (
              <div className="mt-2"><Badge>⚠ Cloudflare token not set (Mailstack → Save settings)</Badge></div>
            ) : null}
          </form>
        </Card>
      </div>
    </Container>
  );
}
